-- Table des tags disponibles
create table tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text default '#6b7280'
);

-- Table de jonction : relation many-to-many entre todos et tags
create table todo_tags (
  todo_id bigint not null references todos(id) on delete cascade,
  tag_id bigint not null references tags(id) on delete cascade,
  primary key (todo_id, tag_id)
);

-- Index pour accélérer les recherches dans les deux sens
create index idx_todo_tags_todo_id on todo_tags(todo_id);
create index idx_todo_tags_tag_id on todo_tags(tag_id);

-- RLS
alter table tags enable row level security;
alter table todo_tags enable row level security;

create policy "Public read access to tags"
on tags for select
using (true);

create policy "Public read access to todo_tags"
on todo_tags for select
using (true);

create policy "Public insert access to tags"
on tags for insert
with check (true);

create policy "Public insert access to todo_tags"
on todo_tags for insert
with check (true);

-- Données de test
insert into tags (name, color) values
  ('CLI', '#3b82f6'),
  ('GitHub', '#10b981'),
  ('Database', '#f59e0b'),
  ('Urgent', '#ef4444');

-- Associations (todo #1 a 2 tags, todo #2 a 2 tags, etc.)
insert into todo_tags (todo_id, tag_id) values
  (1, 1), -- Apprendre Supabase CLI → CLI
  (1, 3), -- Apprendre Supabase CLI → Database
  (2, 2), -- Connecter GitHub → GitHub
  (3, 3), -- Créer une migration → Database
  (4, 3), -- Comprendre RLS → Database
  (4, 4); -- Comprendre RLS → Urgent