-- Test final : valide migration + RLS + CI/CD en une fois
create table final_check (
  id bigint generated by default as identity primary key,
  message text default 'Pipeline Supabase + GitHub validé ✅',
  checked_at timestamptz default now()
);

alter table final_check enable row level security;

create policy "Public read access"
on final_check for select
using (true);

insert into final_check (message) values ('Test CI/CD final réussi');