-- Table liée à todos via foreign key (relation one-to-many)
create table todo_comments (
  id bigint generated by default as identity primary key,
  todo_id bigint not null references todos(id) on delete cascade,
  content text not null,
  created_at timestamptz default now()
);

-- Index pour accélérer les recherches par todo_id
create index idx_todo_comments_todo_id on todo_comments(todo_id);

-- RLS activé
alter table todo_comments enable row level security;

-- Accès public en lecture pour l'apprentissage (à restreindre en vrai projet)
create policy "Public read access to comments"
on todo_comments for select
using (true);

create policy "Public insert access to comments"
on todo_comments for insert
with check (true);

-- Données de test liées aux todos existants (id 1 à 4)
insert into todo_comments (todo_id, content) values
  (1, 'CLI installée avec succès'),
  (1, 'Testé login et init sans problème'),
  (2, 'Connexion GitHub validée dans le dashboard'),
  (3, 'Première migration créée et appliquée');