-- Table simple pour apprendre le workflow Supabase + GitHub
create table todos (
  id bigint generated by default as identity primary key,
  title text not null,
  is_done boolean default false,
  created_at timestamptz default now()
);

-- Active la sécurité au niveau des lignes (bonne pratique)
alter table todos enable row level security;

-- Politique simple : tout le monde peut tout faire (juste pour apprendre, jamais en prod)
create policy "Allow all access to todos"
on todos
for all
using (true)
with check (true);

-- Quelques données de test
insert into todos (title, is_done) values
  ('Apprendre Supabase CLI', true),
  ('Connecter GitHub à Supabase', true),
  ('Créer une migration', false),
  ('Comprendre RLS', false);